image: python:3.8

before_script:
  - pip install --upgrade pip
  - pip install requests
  - pip install mock
  - pip install requests_mock

stages:
  - test

test:
  stage: test
  script:
    - python -m unittest test/test_download_espa_order.py
  tags:
    - docker
    - eros
    - lsrd


